POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYwYTY3MjJmMmY4NDMzMGNmN2E2MGEzZiIsImlhdCI6MTYyMTUyMDk1MX0.FEjEQv38V-wKk164KaeYbokcYaC6fZDpS7z2ZIznJUo

{
    "title": "blogi1",
    "author": "tester",
    "url": "blog.fi/1",
    "likes": 1
}